#!/usr/bin/env bash
# Activate your Python environment first. Positional/CLI arguments are forwarded to the pipeline.
set -euo pipefail
PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
cd "$PROJECT_DIR"
PYTHON="${PYTHON:-python}"
if (( $# > 0 )); then
    exec "$PYTHON" -m Heatmaps.heatmap_training_pipeline "$@"
fi
# Edit these input paths. No installation or checkpoint download is performed here.
RUN_DIR="${RUN_DIR:-$PROJECT_DIR/outputs}"
PRETRAINED_CHECKPOINT="${PRETRAINED_CHECKPOINT:-/path/to/vitpose-b.pth}" # Standard COCO 256x192 pose checkpoint.
FOLD_LISTS_DIR="${FOLD_LISTS_DIR:-$PROJECT_DIR/data/folds}"
MARK_LIST_FILE="${MARK_LIST_FILE:-$PROJECT_DIR/data/doctors_resampled_transverseMarkList.txt}"
IMAGE_DATA_DIR="${IMAGE_DATA_DIR:-$PROJECT_DIR/data/TRANSVERSE}"
REPETITION="${REPETITION:-1}"
FOLD="${FOLD:-1}"
TASK_NAME="${TASK_NAME:-prostate_transverse}"
NUM_POINTS="${NUM_POINTS:-4}"
RESUME_TRAINING="${RESUME_TRAINING:-false}"
DEVICE="${DEVICE:-cuda}"
RUN_NAME="${RUN_NAME:-}"
IMAGE_SIZE="${IMAGE_SIZE:-512}"
HEATMAP_SIGMA="${HEATMAP_SIGMA:-8}"
OVERSAMPLING_FACTOR="${OVERSAMPLING_FACTOR:-8}"
BATCH_SIZE="${BATCH_SIZE:-4}"
MAX_TRAINING_EPOCHS="${MAX_TRAINING_EPOCHS:-300}"
LEARNING_RATE="${LEARNING_RATE:-0.0001}"
ENCODER_LEARNING_RATE="${ENCODER_LEARNING_RATE:-0.00001}"
FREEZE_ENCODER_EPOCHS="${FREEZE_ENCODER_EPOCHS:-5}"
FINETUNE_LAST_BLOCKS="${FINETUNE_LAST_BLOCKS:-12}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-true}"
TRAIN_WORKERS="${TRAIN_WORKERS:-8}"
RANDOM_SEED="${RANDOM_SEED:-42}"
LOSS_NAME="${LOSS_NAME:-weighted_mse}"
LANDMARK_CONSTRAINT_LOSS="${LANDMARK_CONSTRAINT_LOSS:-}" # Empty disables; prostate_taus enables.
POSITIVE_WEIGHT="${POSITIVE_WEIGHT:-20}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.0001}"
LR_SCHEDULE="${LR_SCHEDULE:-plateau}" # plateau, cosine, linear, exponential, step, none
DECODER_PLATEAU_PATIENCE="${DECODER_PLATEAU_PATIENCE:-10}"
DECODER_PLATEAU_MIN_DELTA="${DECODER_PLATEAU_MIN_DELTA:-0.1}"
FINETUNE_DECODER_LR_FACTOR="${FINETUNE_DECODER_LR_FACTOR:-0.5}"
LR_PLATEAU_PATIENCE="${LR_PLATEAU_PATIENCE:-3}"
LR_DECAY_EPOCHS="${LR_DECAY_EPOCHS:-50}"
LR_MIN_FACTOR="${LR_MIN_FACTOR:-0.01}"
LR_STEP_SIZE="${LR_STEP_SIZE:-20}"
LR_GAMMA="${LR_GAMMA:-0.5}"
EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-30}"
EARLY_STOP_MIN_DELTA="${EARLY_STOP_MIN_DELTA:-0.0001}"
EARLY_STOP_WARMUP_EPOCHS="${EARLY_STOP_WARMUP_EPOCHS:-10}"
USE_AMP="${USE_AMP:-false}"
SAVE_VALIDATION_PREDICTIONS="${SAVE_VALIDATION_PREDICTIONS:-true}"
DECODER_CHANNELS="${DECODER_CHANNELS:-256}"
OUTPUT_ACTIVATION="${OUTPUT_ACTIVATION:-none}"
FINAL_KERNEL_SIZE="${FINAL_KERNEL_SIZE:-1}"
VISUALISE_VALIDATION_PROGRESS_IMAGES=0
VISUALISE_VALIDATION_PROGRESS_EPOCHS=0
ARGS=("$REPETITION" "$FOLD" "$TASK_NAME" true false
    --run-dir "$RUN_DIR" --pretrained-checkpoint "$PRETRAINED_CHECKPOINT"
    --num-points "$NUM_POINTS" --fold-lists-path "$FOLD_LISTS_DIR"
    --mark-list-file "$MARK_LIST_FILE" --image-data-dir "$IMAGE_DATA_DIR"
    --resume-training "$RESUME_TRAINING" --device "$DEVICE"
    --network-name vitpose --optimiser-name adamw
    --enforce-greyscale true --normalise-inputs false --recursive-image-search false
    --visualise-validation-progress-images "$VISUALISE_VALIDATION_PROGRESS_IMAGES"
    --visualise-validation-progress-epochs "$VISUALISE_VALIDATION_PROGRESS_EPOCHS"
    --image-size "$IMAGE_SIZE"
    --heatmap-sigma "$HEATMAP_SIGMA"
    --oversampling-factor "$OVERSAMPLING_FACTOR"
    --batch-size "$BATCH_SIZE"
    --max-training-epochs "$MAX_TRAINING_EPOCHS"
    --learning-rate "$LEARNING_RATE"
    --encoder-learning-rate "$ENCODER_LEARNING_RATE"
    --freeze-encoder-epochs "$FREEZE_ENCODER_EPOCHS"
    --finetune-last-blocks "$FINETUNE_LAST_BLOCKS"
    --gradient-checkpointing "$GRADIENT_CHECKPOINTING"
    --train-workers "$TRAIN_WORKERS"
    --random-seed "$RANDOM_SEED"
    --loss-name "$LOSS_NAME"
    --positive-weight "$POSITIVE_WEIGHT"
    --weight-decay "$WEIGHT_DECAY"
    --lr-schedule "$LR_SCHEDULE"
    --decoder-plateau-patience "$DECODER_PLATEAU_PATIENCE"
    --decoder-plateau-min-delta "$DECODER_PLATEAU_MIN_DELTA"
    --finetune-decoder-lr-factor "$FINETUNE_DECODER_LR_FACTOR"
    --lr-plateau-patience "$LR_PLATEAU_PATIENCE"
    --lr-decay-epochs "$LR_DECAY_EPOCHS"
    --lr-min-factor "$LR_MIN_FACTOR"
    --lr-step-size "$LR_STEP_SIZE"
    --lr-gamma "$LR_GAMMA"
    --early-stop-patience "$EARLY_STOP_PATIENCE"
    --early-stop-min-delta "$EARLY_STOP_MIN_DELTA"
    --early-stop-warmup-epochs "$EARLY_STOP_WARMUP_EPOCHS"
    --use-amp "$USE_AMP"
    --save-validation-predictions "$SAVE_VALIDATION_PREDICTIONS"
    --decoder-channels "$DECODER_CHANNELS"
    --output-activation "$OUTPUT_ACTIVATION"
    --final-kernel-size "$FINAL_KERNEL_SIZE"
 )
if [[ -n "$LANDMARK_CONSTRAINT_LOSS" ]]; then ARGS+=(--landmark-constraint-loss "$LANDMARK_CONSTRAINT_LOSS"); fi
if [[ -n "$RUN_NAME" ]]; then ARGS+=(--run-name "$RUN_NAME"); fi
exec "$PYTHON" -u -m Heatmaps.heatmap_training_pipeline "${ARGS[@]}"
